### ISSUE TITLE
Support Other Income endpoint

### ISSUE THREAD

**Issue by amcintosh** [amcintosh/freshbooks-java-sdk#3]
See https://www.freshbooks.com/api/other_income

**Comment by raernon** [comment]
Trying to solve this issue, but the api documentation is inconsistent.
The other_income object has a vis_state field, but the delete function goes with DELETE http method instead of PUT.
Besides this, the delete function doesn't have any return value, just an empty "response" json object.
Does the FreshBooks use the vis_state field in case of other incomes, or just simply delete them?

**Comment by raernon** [comment]
Sorry for the double reference, but the first one cannot be merged automatically to your master branch, so I altered it and pushed it again. Please use the second one, but they are identically the same.
